/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LearningResource = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'difficulty' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'resourceType' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const LearningPreferences = IDL.Record({
  'kinesthetic' : IDL.Bool,
  'auditory' : IDL.Bool,
  'readingWriting' : IDL.Bool,
  'visual' : IDL.Bool,
});
export const StudentProfile = IDL.Record({
  'learningStyle' : LearningPreferences,
  'currentCourses' : IDL.Vec(IDL.Text),
  'interests' : IDL.Vec(IDL.Text),
  'completedCourses' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
});
export const PerformanceRecord = IDL.Record({
  'completedResources' : IDL.Vec(IDL.Text),
  'score' : IDL.Nat,
  'studyTime' : IDL.Nat,
  'course' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResource' : IDL.Func([IDL.Text, LearningResource], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteResource' : IDL.Func([IDL.Text], [], []),
  'editResource' : IDL.Func([IDL.Text, LearningResource], [], []),
  'getAllResources' : IDL.Func([], [IDL.Vec(LearningResource)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPerformance' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PerformanceRecord)],
      ['query'],
    ),
  'getRecommendations' : IDL.Func([], [IDL.Vec(LearningResource)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(StudentProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
  'updatePerformance' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LearningResource = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'difficulty' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'resourceType' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const LearningPreferences = IDL.Record({
    'kinesthetic' : IDL.Bool,
    'auditory' : IDL.Bool,
    'readingWriting' : IDL.Bool,
    'visual' : IDL.Bool,
  });
  const StudentProfile = IDL.Record({
    'learningStyle' : LearningPreferences,
    'currentCourses' : IDL.Vec(IDL.Text),
    'interests' : IDL.Vec(IDL.Text),
    'completedCourses' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
  });
  const PerformanceRecord = IDL.Record({
    'completedResources' : IDL.Vec(IDL.Text),
    'score' : IDL.Nat,
    'studyTime' : IDL.Nat,
    'course' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResource' : IDL.Func([IDL.Text, LearningResource], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteResource' : IDL.Func([IDL.Text], [], []),
    'editResource' : IDL.Func([IDL.Text, LearningResource], [], []),
    'getAllResources' : IDL.Func([], [IDL.Vec(LearningResource)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(StudentProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPerformance' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PerformanceRecord)],
        ['query'],
      ),
    'getRecommendations' : IDL.Func([], [IDL.Vec(LearningResource)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(StudentProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([StudentProfile], [], []),
    'updatePerformance' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };