/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LearningPreferences {
  'kinesthetic' : boolean,
  'auditory' : boolean,
  'readingWriting' : boolean,
  'visual' : boolean,
}
export interface LearningResource {
  'title' : string,
  'duration' : bigint,
  'difficulty' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'resourceType' : string,
  'category' : string,
}
export interface PerformanceRecord {
  'completedResources' : Array<string>,
  'score' : bigint,
  'studyTime' : bigint,
  'course' : string,
}
export interface StudentProfile {
  'learningStyle' : LearningPreferences,
  'currentCourses' : Array<string>,
  'interests' : Array<string>,
  'completedCourses' : Array<string>,
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResource' : ActorMethod<[string, LearningResource], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteResource' : ActorMethod<[string], undefined>,
  'editResource' : ActorMethod<[string, LearningResource], undefined>,
  'getAllResources' : ActorMethod<[], Array<LearningResource>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [StudentProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPerformance' : ActorMethod<[Principal], Array<PerformanceRecord>>,
  'getRecommendations' : ActorMethod<[], Array<LearningResource>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [StudentProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[StudentProfile], undefined>,
  'updatePerformance' : ActorMethod<
    [string, bigint, bigint, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];